; N64 'Bare Metal' 32BPP 320x240 Cycle1 Fill ZBuffer Triangle RDP Demo by krom (Peter Lemon):

  include LIB\N64.INC ; Include N64 Definitions
  dcb 2097152,$00 ; Set ROM Size
  org $80000000 ; Entry Point Of Code
  include LIB\N64_HEADER.ASM  ; Include 64 Byte Header & Vector Table
  incbin LIB\N64_BOOTCODE.BIN ; Include 4032 Byte Boot Code

Start:
  include LIB\N64_INIT.ASM ; Include Initialisation Routine
  include LIB\N64_GFX.INC  ; Include Graphics Macros

  ScreenNTSC 320,240, BPP32, $A0100000 ; Screen NTSC: 320x240, 32BPP, DRAM Origin $A0100000

  WaitScanline $200 ; Wait For Scanline To Reach Vertical Blank

  DPC RDPBuffer,RDPBufferEnd ; Run DPC Command Buffer: Start Address, End Address

Loop:
  j Loop
  nop ; Delay Slot

  align 8 ; Align 64-bit
RDPBuffer:
  Set_Scissor 0<<2,0<<2, 320<<2,240<<2, 0 ; Set Scissor: XH 0.0, YH 0.0, XL 320.0, YL 240.0, Scissor Field Enable Off
  Set_Other_Modes CYCLE_TYPE_FILL, 0 ; Set Other Modes
  Set_Z_Image $00200000 ; Set Z Image: DRAM ADDRESS $00200000
  Set_Color_Image SIZE_OF_PIXEL_16B|(320-1), $00200000 ; Set Color Image: SIZE 16B, WIDTH 320, DRAM ADDRESS $00200000
  Set_Fill_Color $FFFFFFFF ; Set Fill Color: PACKED COLOR 16B R5G5B5A1 Pixels (Clear ZBuffer)
  Fill_Rectangle 319<<2,239<<2, 0<<2,0<<2 ; Fill Rectangle: XL 319.0, YL 239.0, XH 0.0, YH 0.0

  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Color_Image SIZE_OF_PIXEL_32B|(320-1), $00100000 ; Set Color Image: SIZE 32B, WIDTH 320, DRAM ADDRESS $00100000
  Set_Fill_Color $FFFF00FF ; Set Fill Color: PACKED COLOR 32B R8G8B8A8 Pixel
  Fill_Rectangle 319<<2,239<<2, 0<<2,0<<2 ; Fill Rectangle: XL 319.0, YL 239.0, XH 0.0, YH 0.0

  Set_Other_Modes SAMPLE_TYPE|BI_LERP_0|ALPHA_DITHER_SEL_NO_DITHER, B_M1A_0_2|IMAGE_READ_EN|Z_COMPARE_EN|Z_UPDATE_EN ; Set Other Modes
  Set_Combine_Mode $0, $00, 0, 0, $1, $01, $0, $F, 1, 0, 0, 0, 0, 7, 7, 7 ; Set Combine Mode: SubA RGB0, MulRGB0, SubA Alpha0, MulAlpha0, SubA RGB1, MulRGB1, SubB RGB0, SubB RGB1, SubA Alpha1, MulAlpha1, AddRGB0, SubB Alpha0, AddAlpha0, AddRGB1, SubB Alpha1, AddAlpha1


  Set_Blend_Color $FF0000FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Red)
  ;
  ;      DxHDy
  ;    ._______. v[2]:XH,XM(X:25.0) YH(Y:50.0), v[1]:XL(X:75.0) YM(Y:50.0) (Z:100.0)
  ;     \     /
  ; DxMDy\   /DxLDy
  ;       \ /    v[0]:(X:50.0) YL(Y:75.0) (Z:0.0)
  ;        .
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 75.0, YM 50.0, YH 50.0, XL 75.0, DxLDy -1.0, XH 25.0, DxHDy 0.0, XM 25.0, DxMDy 0.0
    Fill_ZBuffer_Triangle 1, 0, 0, 300,200,200, 75,0, -1,0, 25,0, 1,0, 25,0, 0,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 100.0, DzDx 0.0, DzDe -8.0, DzDy 0.0
    ZBuffer_Coefficients 100,0,0,0, -8,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf

  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $00FF00FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Green)
  ;
  ;        .     v[2]:XH,XM(X:50.0) YH(Y:25.0) (Z:50.0)
  ;       / \
  ; DxMDy/   \DxHDy
  ;     /     \  
  ;    ._______. v[0]:(X:25.0) YL(Y:100.0), v[1]:XL(X:75.0) YM(Y:100.0) (Z:50.0)
  ;      DxLDy
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 100.0, YM 100.0, YH 25.0, XL 75.0, DxLDy 0.0, XH 50.0, DxHDy -0.333333, XM 50.0, DxMDy 0.333333
    Fill_ZBuffer_Triangle 1, 0, 0, 400,400,100, 75,0, 0,0, 50,0, -1,43690, 50,0, 0,21845 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 50.0, DzDx 0.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 50,0,0,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf


  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $FF0000FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Red)
  ;
  ;      DxHDy
  ;    ._______. v[2]:XH,XM(X:100.0) YH(Y:50.0), v[1]:XL(X:150.0) YM(Y:50.0) (Z:0.0)
  ;     \     /
  ; DxMDy\   /DxLDy
  ;       \ /    v[0]:(X:125.0) YL(Y:75.0) (Z:100.0)
  ;        .
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 75.0, YM 50.0, YH 150.0, XL 75.0, DxLDy -1.0, XH 100.0, DxHDy 0.0, XM 100.0, DxMDy 0.0
    Fill_ZBuffer_Triangle 1, 0, 0, 300,200,200, 150,0, -1,0, 100,0, 1,0, 100,0, 0,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 0.0, DzDx 0.0, DzDe 8.0, DzDy 0.0
    ZBuffer_Coefficients 0,0,0,0, 8,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf

  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $00FF00FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Green)
  ;
  ;        .     v[2]:XH,XM(X:125.0) YH(Y:25.0) (Z:50.0)
  ;       / \
  ; DxMDy/   \DxHDy
  ;     /     \  
  ;    ._______. v[0]:(X:100.0) YL(Y:100.0), v[1]:XL(X:150.0) YM(Y:100.0) (Z:50.0)
  ;      DxLDy
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 100.0, YM 100.0, YH 25.0, XL 150.0, DxLDy 0.0, XH 125.0, DxHDy -0.333333, XM 125.0, DxMDy 0.333333
    Fill_ZBuffer_Triangle 1, 0, 0, 400,400,100, 150,0, 0,0, 125,0, -1,43690, 125,0, 0,21845 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 50.0, DzDx 0.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 50,0,0,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf


  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $FF0000FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Red)
  ;
  ;      .    v[2]:XH,XM(X:175.0) YH(Y:50.0) (Z:100.0)
  ;      |\DxHDy
  ;      | \
  ; DxMDy|  . v[1]:XL(X:200.0) YM(Y:75.0) (Z:0.0)
  ;      | /DxLDy
  ;      ./   v[0]:(X:175.0) YL(Y:100.0) (Z:100.0)
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 100.0, YM 75.0, YH 50.0, XL 200.0, DxLDy -1.0, XH 175.0, DxHDy 0.0, XM 175.0, DxMDy 1.0
    Fill_ZBuffer_Triangle 1, 0, 0, 400,300,200, 200,0, -1,0, 175,0, 0,0, 175,0, 1,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 100.0, DzDx -8.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 100,0,-8,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf

  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $00FF00FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Green)
  ;
  ;        . v[2]:XH,XM(X:225.0) YH(Y:50.0) (Z:50.0)
  ;       /|
  ; DxHDy/ |DxMDy
  ;     .  | v[1]:XL(X:150.0) YM(Y:75.0) (Z:50.0)
  ; DxLDy\ |
  ;       \. v[0]:(X:225.0) YL(Y:100.0) (Z:50.0)
  ;
  ; Output: Dir 0, Level 0, Tile 0, YL 100.0, YM 75.0, YH 50.0, XL 150.0, DxLDy 3.0, XH 225.0, DxHDy 0.0, XM 225.0, DxMDy -3.0
    Fill_ZBuffer_Triangle 0, 0, 0, 400,300,200, 150,0, 3,0, 225,0, 0,0, 225,0, -3,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 50.0, DzDx 0.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 50,0,0,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf


  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $FF0000FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Red)
  ;
  ;      .    v[2]:XH,XM(X:250.0) YH(Y:50.0) (Z:0.0)
  ;      |\DxHDy
  ;      | \
  ; DxMDy|  . v[1]:XL(X:275.0) YM(Y:75.0) (Z:100.0)
  ;      | /DxLDy
  ;      ./   v[0]:(X:250.0) YL(Y:100.0) (Z:0.0)
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 100.0, YM 75.0, YH 50.0, XL 275.0, DxLDy -1.0, XH 250.0, DxHDy 0.0, XM 250.0, DxMDy 1.0
    Fill_ZBuffer_Triangle 1, 0, 0, 400,300,200, 275,0, -1,0, 250,0, 0,0, 250,0, 1,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 0.0, DzDx 8.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 0,0,8,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf

  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $00FF00FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Green)
  ;
  ;        . v[2]:XH,XM(X:300.0) YH(Y:50.0) (Z:50.0)
  ;       /|
  ; DxHDy/ |DxMDy
  ;     .  | v[1]:XL(X:225.0) YM(Y:75.0) (Z:50.0)
  ; DxLDy\ |
  ;       \. v[0]:(X:300.0) YL(Y:100.0) (Z:50.0)
  ;
  ; Output: Dir 0, Level 0, Tile 0, YL 100.0, YM 75.0, YH 50.0, XL 225.0, DxLDy 3.0, XH 300.0, DxHDy 0.0, XM 300.0, DxMDy -3.0
    Fill_ZBuffer_Triangle 0, 0, 0, 400,300,200, 225,0, 3,0, 300,0, 0,0, 300,0, -3,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 50.0, DzDx 0.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 50,0,0,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf


  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Other_Modes SAMPLE_TYPE|BI_LERP_0|ALPHA_DITHER_SEL_NO_DITHER, B_M1A_0_2|IMAGE_READ_EN|Z_SOURCE_SEL|Z_COMPARE_EN|Z_UPDATE_EN ; Set Other Modes

  Set_Blend_Color $FF0000FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Red)
  Set_Prim_Depth 50,0 ; Set Primitive Depth: PRIMITIVE Z 50, PRIMITIVE DELTA Z 0
  ;
  ;      DxHDy
  ;    ._______. v[2]:XH,XM(X:25.0) YH(Y:150.0), v[1]:XL(X:75.0) YM(Y:150.0) (Z:50.0)
  ;     \     /
  ; DxMDy\   /DxLDy
  ;       \ /    v[0]:(X:50.0) YL(Y:175.0) (Z:50.0)
  ;        .
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 175.0, YM 150.0, YH 150.0, XL 75.0, DxLDy -1.0, XH 25.0, DxHDy 0.0, XM 25.0, DxMDy 0.0
    Fill_ZBuffer_Triangle 1, 0, 0, 700,600,600, 75,0, -1,0, 25,0, 1,0, 25,0, 0,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 100.0, DzDx 0.0, DzDe -8.0, DzDy 0.0
    ZBuffer_Coefficients 100,0,0,0, -8,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf

  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $00FF00FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Green)
  Set_Prim_Depth 100,0 ; Set Primitive Depth: PRIMITIVE Z 100, PRIMITIVE DELTA Z 0
  ;
  ;        .     v[2]:XH,XM(X:50.0) YH(Y:125.0) (Z:100.0)
  ;       / \
  ; DxMDy/   \DxHDy
  ;     /     \  
  ;    ._______. v[0]:(X:25.0) YL(Y:200.0), v[1]:XL(X:75.0) YM(Y:200.0) (Z:100.0)
  ;      DxLDy
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 200.0, YM 200.0, YH 125.0, XL 75.0, DxLDy 0.0, XH 50.0, DxHDy -0.333333, XM 50.0, DxMDy 0.333333
    Fill_ZBuffer_Triangle 1, 0, 0, 800,800,500, 75,0, 0,0, 50,0, -1,43690, 50,0, 0,21845 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 50.0, DzDx 0.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 50,0,0,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf


  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $FF0000FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Red)
  Set_Prim_Depth 100,0 ; Set Primitive Depth: PRIMITIVE Z 100, PRIMITIVE DELTA Z 0
  ;
  ;      DxHDy
  ;    ._______. v[2]:XH,XM(X:100.0) YH(Y:150.0), v[1]:XL(X:150.0) YM(Y:150.0) (Z:100.0)
  ;     \     /
  ; DxMDy\   /DxLDy
  ;       \ /    v[0]:(X:125.0) YL(Y:175.0) (Z:100.0)
  ;        .
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 175.0, YM 150.0, YH 150.0, XL 75.0, DxLDy -1.0, XH 100.0, DxHDy 0.0, XM 100.0, DxMDy 0.0
    Fill_ZBuffer_Triangle 1, 0, 0, 700,600,600, 150,0, -1,0, 100,0, 1,0, 100,0, 0,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 0.0, DzDx 0.0, DzDe 8.0, DzDy 0.0
    ZBuffer_Coefficients 0,0,0,0, 8,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf

  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $00FF00FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Green)
  Set_Prim_Depth 50,0 ; Set Primitive Depth: PRIMITIVE Z 50, PRIMITIVE DELTA Z 0
  ;
  ;        .     v[2]:XH,XM(X:125.0) YH(Y:125.0) (Z:50.0)
  ;       / \
  ; DxMDy/   \DxHDy
  ;     /     \  
  ;    ._______. v[0]:(X:100.0) YL(Y:200.0), v[1]:XL(X:150.0) YM(Y:200.0) (Z:50.0)
  ;      DxLDy
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 200.0, YM 200.0, YH 125.0, XL 150.0, DxLDy 0.0, XH 125.0, DxHDy -0.333333, XM 125.0, DxMDy 0.333333
    Fill_ZBuffer_Triangle 1, 0, 0, 800,800,500, 150,0, 0,0, 125,0, -1,43690, 125,0, 0,21845 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 50.0, DzDx 0.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 50,0,0,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf


  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $FF0000FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Red)
  Set_Prim_Depth 50,0 ; Set Primitive Depth: PRIMITIVE Z 50, PRIMITIVE DELTA Z 0
  ;
  ;      .    v[2]:XH,XM(X:175.0) YH(Y:150.0) (Z:50.0)
  ;      |\DxHDy
  ;      | \
  ; DxMDy|  . v[1]:XL(X:200.0) YM(Y:175.0) (Z:50.0)
  ;      | /DxLDy
  ;      ./   v[0]:(X:175.0) YL(Y:200.0) (Z:50.0)
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 200.0, YM 175.0, YH 150.0, XL 200.0, DxLDy -1.0, XH 175.0, DxHDy 0.0, XM 175.0, DxMDy 1.0
    Fill_ZBuffer_Triangle 1, 0, 0, 800,700,600, 200,0, -1,0, 175,0, 0,0, 175,0, 1,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 100.0, DzDx -8.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 100,0,-8,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf

  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $00FF00FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Green)
  Set_Prim_Depth 100,0 ; Set Primitive Depth: PRIMITIVE Z 100, PRIMITIVE DELTA Z 0
  ;
  ;        . v[2]:XH,XM(X:225.0) YH(Y:150.0) (Z:100.0)
  ;       /|
  ; DxHDy/ |DxMDy
  ;     .  | v[1]:XL(X:150.0) YM(Y:175.0) (Z:100.0)
  ; DxLDy\ |
  ;       \. v[0]:(X:225.0) YL(Y:200.0) (Z:100.0)
  ;
  ; Output: Dir 0, Level 0, Tile 0, YL 200.0, YM 175.0, YH 150.0, XL 150.0, DxLDy 3.0, XH 225.0, DxHDy 0.0, XM 225.0, DxMDy -3.0
    Fill_ZBuffer_Triangle 0, 0, 0, 800,700,600, 150,0, 3,0, 225,0, 0,0, 225,0, -3,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 50.0, DzDx 0.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 50,0,0,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf


  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $FF0000FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Red)
  Set_Prim_Depth 100,0 ; Set Primitive Depth: PRIMITIVE Z 100, PRIMITIVE DELTA Z 0
  ;
  ;      .    v[2]:XH,XM(X:250.0) YH(Y:150.0) (Z:100.0)
  ;      |\DxHDy
  ;      | \
  ; DxMDy|  . v[1]:XL(X:275.0) YM(Y:175.0) (Z:100.0)
  ;      | /DxLDy
  ;      ./   v[0]:(X:250.0) YL(Y:200.0) (Z:100.0)
  ;
  ; Output: Dir 1, Level 0, Tile 0, YL 200.0, YM 175.0, YH 150.0, XL 275.0, DxLDy -1.0, XH 250.0, DxHDy 0.0, XM 250.0, DxMDy 1.0
    Fill_ZBuffer_Triangle 1, 0, 0, 800,700,600, 275,0, -1,0, 250,0, 0,0, 250,0, 1,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 0.0, DzDx 8.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 0,0,8,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf

  Sync_Pipe ; Stall Pipeline, Until Preceeding Primitives Completely Finish
  Set_Blend_Color $00FF00FF ; Set Blend Color: R 255, G 0, B 0, A 255 (Green)
  Set_Prim_Depth 50,0 ; Set Primitive Depth: PRIMITIVE Z 50, PRIMITIVE DELTA Z 0
  ;
  ;        . v[2]:XH,XM(X:300.0) YH(Y:150.0) (Z:50.0)
  ;       /|
  ; DxHDy/ |DxMDy
  ;     .  | v[1]:XL(X:225.0) YM(Y:175.0) (Z:50.0)
  ; DxLDy\ |
  ;       \. v[0]:(X:300.0) YL(Y:200.0) (Z:50.0)
  ;
  ; Output: Dir 0, Level 0, Tile 0, YL 200.0, YM 175.0, YH 150.0, XL 225.0, DxLDy 3.0, XH 300.0, DxHDy 0.0, XM 300.0, DxMDy -3.0
    Fill_ZBuffer_Triangle 0, 0, 0, 800,700,600, 225,0, 3,0, 300,0, 0,0, 300,0, -3,0 ; Generated By N64RightMajorTriangleCalc.py
  ; Output: Z 50.0, DzDx 0.0, DzDe 0.0, DzDy 0.0
    ZBuffer_Coefficients 50,0,0,0, 0,0,0,0 ; Z,Zf,DzDx,DzDxf, DzDe,DzDef,DzDy,DzDyf

  Sync_Full ; Ensure Entire Scene Is Fully Drawn
RDPBufferEnd: